name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Release ]
        compiler: [ g++, clang++ ]
        build_dir: [ build ]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      COMPILER: ${{ matrix.compiler }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install apt dependencies
        run: |
          sudo apt update
          sudo apt install -y clang libgtest-dev libgoogle-glog-dev libeigen3-dev 

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_COMPILER=/usr/bin/${{env.COMPILER}} \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C -V ${{env.BUILD_TYPE}}
